server:
  port: 9000
spring:
  application:
      name: cpm-back-end
  #数据源
  datasource:
      hikari:
          connection-test-query: SELECT 1
          idle-timeout: -1
      dynamic:
          primary: mysql-development
          strict: true #不严格匹配数据源
          datasource:
            #开发数据源
            mysql-development:
              url: jdbc:mysql://192.168.0.6:3306/cpm-dev
              username: root
              password: MysqlSunyinuo15332
              driver-class-name: com.mysql.cj.jdbc.Driver
  # redis caching
  cache:
      type: redis
  redis:
      host: 192.168.0.6
      port: 6379
      database: 0
      username: default
      password: redis_HJAZhN
      timeout: 3000ms
      lettuce:
          pool:
            max-active: 10
            max-idle: 10
            max-wait: 3000ms
            min-idle: 20
# log4j2
logging:
    level:
      cn.jay.repository: trace